# Generated by Django 4.0.5 on 2022-06-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_food_image_relative_url_alter_food_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
