# Generated by Django 4.0.5 on 2022-06-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0001_initial'),
        ('app_gen', '0002_subscription_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_foods.food'),
        ),
    ]
